#!/usr/bin/env bash
# brain-link.sh — wire the gamebook brain into a project's Claude memory dir.
#
# Canonical memories live in gamebook/brain/{shared,projects/<ns>}/ (git-tracked,
# shareable). The harness still reads a project's local memory dir, so this script
# keeps the two in sync:
#
#   1. ABSORB  — any REAL (non-symlink) *.md the harness wrote into the memory dir
#                is moved into the brain: shared/ when metadata.type is user|feedback,
#                else projects/<ns>/. New memories thus join the shareable brain.
#   2. LINK    — symlink shared/* and projects/<ns>/* into the memory dir.
#   3. INDEX   — regenerate the memory dir's MEMORY.md from linked files' frontmatter.
#
# Idempotent. Run it manually, from a Stop hook, or to onboard a new repo/teammate:
#
#   bash ~/.claude/gamebook/scripts/brain-link.sh my-game-project
#   bash ~/.claude/gamebook/scripts/brain-link.sh <namespace> [memory-dir]
#
# namespace   selects projects/<namespace>/ (e.g. citadel-lite)
# memory-dir  default: $HOME/.claude/projects/<encoded-cwd>/memory

set -uo pipefail

NS="${1:-}"
if [ -z "$NS" ]; then
  echo "usage: brain-link.sh <namespace> [memory-dir]" >&2
  exit 2
fi

GAMEBOOK="${GAMEBOOK:-$HOME/.claude/gamebook}"
BRAIN="$GAMEBOOK/brain"
SHARED="$BRAIN/shared"
PROJ="$BRAIN/projects/$NS"

# Resolve the harness memory dir. Default: encode $PWD the way the harness does
# (path with every '/' -> '-'), under ~/.claude/projects/<encoded>/memory.
if [ -n "${2:-}" ]; then
  MEM="$2"
else
  encoded="$(printf '%s' "$PWD" | sed 's#/#-#g')"
  MEM="$HOME/.claude/projects/${encoded}/memory"
fi

mkdir -p "$SHARED" "$PROJ" "$MEM"

# Pull a frontmatter scalar (name/description) or a metadata.type from a file.
fm() {  # fm <file> <key>
  awk -v k="$2" '
    /^---[[:space:]]*$/ { d++; next }
    d==1 && $0 ~ "^"k":" { sub("^"k":[[:space:]]*", ""); print; exit }
  ' "$1"
}
fm_type() {  # metadata.type (one level of nesting)
  awk '
    /^---[[:space:]]*$/ { d++; next }
    d==1 && /^[[:space:]]+type:/ { sub(/^[[:space:]]*type:[[:space:]]*/, ""); print; exit }
  ' "$1"
}
slug() { printf '%s' "$1" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-'; }

# ── 1. ABSORB real files the harness wrote since last link ──────────────
absorbed=0
shopt -s nullglob
for f in "$MEM"/*.md; do
  base="$(basename "$f")"
  [ "$base" = "MEMORY.md" ] && continue
  [ -L "$f" ] && continue              # already a brain symlink — skip
  name="$(fm "$f" name)"; [ -z "$name" ] && name="$(slug "${base%.md}")"
  type="$(fm_type "$f")"
  case "$type" in
    user|feedback) dest="$SHARED/$(slug "$name").md" ;;
    *)             dest="$PROJ/$(slug "$name").md" ;;
  esac
  if [ -e "$dest" ] && ! cmp -s "$f" "$dest"; then
    echo "  ! conflict: $base vs $(basename "$dest") — leaving in place" >&2
    continue
  fi
  mv -f "$f" "$dest"
  absorbed=$((absorbed+1))
done

# ── 2. LINK brain files into the memory dir ─────────────────────────────
# Drop stale brain symlinks first (so deletions/renames propagate).
for l in "$MEM"/*.md; do
  [ -L "$l" ] || continue
  tgt="$(readlink "$l")"
  case "$tgt" in "$BRAIN"/*) rm -f "$l" ;; esac
done
linked=0
for f in "$SHARED"/*.md "$PROJ"/*.md; do
  [ -e "$f" ] || continue
  ln -sfn "$f" "$MEM/$(basename "$f")"
  linked=$((linked+1))
done

# ── 3. INDEX — regenerate MEMORY.md ─────────────────────────────────────
INDEX="$MEM/MEMORY.md"
{
  echo "<!-- AUTO-GENERATED by gamebook/scripts/brain-link.sh — edit memories in"
  echo "     gamebook/brain/, not here. Re-run brain-link.sh to refresh. -->"
  echo
  echo "## Shared (how-I-work — every project)"
  for f in "$SHARED"/*.md; do
    [ -e "$f" ] || continue
    nm="$(fm "$f" name)"; [ -z "$nm" ] && nm="$(basename "${f%.md}")"
    ds="$(fm "$f" description)"
    echo "- [$nm]($(basename "$f")) — ${ds:-}"
  done
  echo
  echo "## Project — $NS"
  for f in "$PROJ"/*.md; do
    [ -e "$f" ] || continue
    nm="$(fm "$f" name)"; [ -z "$nm" ] && nm="$(basename "${f%.md}")"
    ds="$(fm "$f" description)"
    echo "- [$nm]($(basename "$f")) — ${ds:-}"
  done
} > "$INDEX"

echo "brain-link[$NS]: absorbed=$absorbed linked=$linked  mem=$MEM"
